### PR TITLE
Fix Mobile Wobblage

### LINKED ISSUE #49: Page "wobbles" on mobile.
- page can be moved from side to side on mobile.

### PR DESCRIPTION
**Pull request by mikeyhogarth**
Fixes #49

### CODE REVIEW

File: src/components/CocktailList.js [hunk 1]
```diff
@@ -12,37 +12,26 @@ const styles = theme => ({
...
 });
 
 const CocktailList = ({ classes, cocktails = [] }) => {
   return (
-    <div className={classes.root}>
+    <div>
       <div className={classes.content}>
         {cocktails.length > 0 && (
-          <GridList className={classes.gridList}>
+          <GridList spacing={0} className={classes.gridList}>
```
Comment (mikeyhogarth) [inline src/components/CocktailList.js]: This is what was causing it, for anyone who's interested.
